#!/bin/bash
# Tests for tools/generate-stable-netplan.sh
#
# Each scenario fully specifies its input topology (a synthetic
# /sys/class/net tree) and its full expected rendered netplan
# output. The actual rendered output is compared verbatim against
# the expected output (the timestamp on the first comment line is
# normalized to a fixed placeholder).
#
# Run: bash tests/test-generate-stable-netplan.sh

set -eu

SCRIPT_DIR=$(cd "$(dirname "$0")/.." && pwd)
# shellcheck source=../tools/generate-stable-netplan.sh
. "${SCRIPT_DIR}/tools/generate-stable-netplan.sh"

PASS=0
FAIL=0

# make_nic <root> <ifname> <mac> <driver> [master_ifname] [dev_port] [shared_device]
#   - master_ifname: if set, create <ifname>/master -> ../<master_ifname>
#     (used to mark transparent VFs).
#   - dev_port: integer written to <ifname>/dev_port (default unset,
#     which the script treats as 0).
#   - shared_device: if set, <ifname>/device symlinks to
#     <root>/devices/<shared_device> instead of a private dir. Use to
#     simulate multi-port NICs where two interfaces share a parent
#     PCI device and are disambiguated only by dev_port (e.g. ens1
#     and ens1d1 on Azure mana NICs).
make_nic() {
    local root=$1 ifname=$2 mac=$3 driver=$4
    local master=${5:-} dev_port=${6:-} shared=${7:-}
    mkdir -p "${root}/${ifname}" "${root}/drivers/${driver}"
    if [ -n "${shared}" ]; then
        mkdir -p "${root}/devices/${shared}"
        ln -sf "../devices/${shared}" "${root}/${ifname}/device"
        ln -sf "../../drivers/${driver}" "${root}/devices/${shared}/driver"
    else
        mkdir -p "${root}/${ifname}/device"
        ln -sf "../../drivers/${driver}" "${root}/${ifname}/device/driver"
    fi
    echo "${mac}" > "${root}/${ifname}/address"
    echo 1        > "${root}/${ifname}/type"
    [ -n "${dev_port}" ] && echo "${dev_port}" > "${root}/${ifname}/dev_port"
    [ -n "${master}" ] && ln -sf "../${master}" "${root}/${ifname}/master"
}

make_lo() {
    local root=$1
    mkdir -p "${root}/lo"
    echo 00:00:00:00:00:00 > "${root}/lo/address"
    echo 772                > "${root}/lo/type"
}

# Header used by every expected output. Real output has a UTC
# timestamp on the first line; normalize_actual rewrites it to
# this fixed string before comparison.
HEADER='# Generated by generate-stable-netplan.sh on TIMESTAMP.
# Mirrors cloud-init PR #6807 (apply_network_config_set_name=false):
# enx<MAC> stanzas, MAC + driver match, no set-name (kernel keeps
# eth0/etc). Driver match is required to avoid binding to the AN VF.
network:
  version: 2
  renderer: networkd
  ethernets:'

normalize_actual() {
    sed -E 's/ on [0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9:]+Z\./ on TIMESTAMP./'
}

# render_for <setup_fn>
#   Build the sysfs tree, run the script's pipeline, and print the
#   normalized rendered netplan to stdout.
render_for() {
    local setup_fn=$1 tmp nics primary
    tmp=$(mktemp -d)
    make_lo "${tmp}"
    "${setup_fn}" "${tmp}"
    nics=$(SYSFS_NET="${tmp}" enumerate_nics)
    primary=$(printf '%s\n' "${nics}" | pick_primary_mac)
    render_netplan "${primary}" "${nics}" | normalize_actual
    rm -rf "${tmp}"
}

# run_test <name> <setup_fn> <expected>
run_test() {
    local name=$1 setup_fn=$2 expected=$3 actual
    actual=$(render_for "${setup_fn}")
    if [ "${expected}" = "${actual}" ]; then
        PASS=$((PASS + 1))
        echo "ok  - ${name}"
    else
        FAIL=$((FAIL + 1))
        echo "FAIL - ${name}"
        diff <(printf '%s\n' "${expected}") <(printf '%s\n' "${actual}") \
            | sed 's/^/    /'
    fi
}

# ---- Scenarios -----------------------------------------------------

# 1 NIC, no AN -------------------------------------------------------
setup_1nic_no_an() {
    make_nic "$1" eth0 00:0d:3a:00:00:01 hv_netvsc
}
expected_1nic_no_an="${HEADER}
    enx000d3a000001:
      match:
        macaddress: 00:0d:3a:00:00:01
        driver: hv_netvsc
      dhcp4: true
      dhcp4-overrides:
        route-metric: 100
      dhcp6: false"

# 2 NICs, no AN ------------------------------------------------------
setup_2nic_no_an() {
    make_nic "$1" eth0 00:0d:3a:00:00:01 hv_netvsc
    make_nic "$1" eth1 00:0d:3a:00:00:02 hv_netvsc
}
expected_2nic_no_an="${HEADER}
    enx000d3a000001:
      match:
        macaddress: 00:0d:3a:00:00:01
        driver: hv_netvsc
      dhcp4: true
      dhcp4-overrides:
        route-metric: 100
      dhcp6: false
    enx000d3a000002:
      match:
        macaddress: 00:0d:3a:00:00:02
        driver: hv_netvsc
      dhcp4: true
      dhcp4-overrides:
        route-metric: 200
        use-dns: false
      dhcp6: false"

# 4 NICs, no AN ------------------------------------------------------
setup_4nic_no_an() {
    make_nic "$1" eth0 00:0d:3a:00:00:01 hv_netvsc
    make_nic "$1" eth1 00:0d:3a:00:00:02 hv_netvsc
    make_nic "$1" eth2 00:0d:3a:00:00:03 hv_netvsc
    make_nic "$1" eth3 00:0d:3a:00:00:04 hv_netvsc
}
expected_4nic_no_an="${HEADER}
    enx000d3a000001:
      match:
        macaddress: 00:0d:3a:00:00:01
        driver: hv_netvsc
      dhcp4: true
      dhcp4-overrides:
        route-metric: 100
      dhcp6: false
    enx000d3a000002:
      match:
        macaddress: 00:0d:3a:00:00:02
        driver: hv_netvsc
      dhcp4: true
      dhcp4-overrides:
        route-metric: 200
        use-dns: false
      dhcp6: false
    enx000d3a000003:
      match:
        macaddress: 00:0d:3a:00:00:03
        driver: hv_netvsc
      dhcp4: true
      dhcp4-overrides:
        route-metric: 300
        use-dns: false
      dhcp6: false
    enx000d3a000004:
      match:
        macaddress: 00:0d:3a:00:00:04
        driver: hv_netvsc
      dhcp4: true
      dhcp4-overrides:
        route-metric: 400
        use-dns: false
      dhcp6: false"

# 2 NICs, mlx5 AN (each synthetic has an mlx5_core VF sibling) -------
setup_2nic_mlx_an() {
    make_nic "$1" eth0   00:0d:3a:00:00:01 hv_netvsc
    make_nic "$1" enP1s1 00:0d:3a:00:00:01 mlx5_core eth0
    make_nic "$1" eth1   00:0d:3a:00:00:02 hv_netvsc
    make_nic "$1" enP2s1 00:0d:3a:00:00:02 mlx5_core eth1
}
# VFs are filtered by the `master` symlink, so the rendered output
# is identical to the no-AN case — driver pinned to hv_netvsc.
expected_2nic_mlx_an="${expected_2nic_no_an}"

# 2 NICs, mana AN ----------------------------------------------------
setup_2nic_mana_an() {
    make_nic "$1" eth0   00:0d:3a:00:00:01 hv_netvsc
    make_nic "$1" enP1s1 00:0d:3a:00:00:01 mana eth0
    make_nic "$1" eth1   00:0d:3a:00:00:02 hv_netvsc
    make_nic "$1" enP2s1 00:0d:3a:00:00:02 mana eth1
}
expected_2nic_mana_an="${expected_2nic_no_an}"

# 2 NICs, mana-only (future SKU, no hv_netvsc) -----------------------
setup_2nic_mana_only() {
    make_nic "$1" eth0 00:0d:3a:00:00:01 mana
    make_nic "$1" eth1 00:0d:3a:00:00:02 mana
}
expected_2nic_mana_only="${HEADER}
    enx000d3a000001:
      match:
        macaddress: 00:0d:3a:00:00:01
        driver: mana
      dhcp4: true
      dhcp4-overrides:
        route-metric: 100
      dhcp6: false
    enx000d3a000002:
      match:
        macaddress: 00:0d:3a:00:00:02
        driver: mana
      dhcp4: true
      dhcp4-overrides:
        route-metric: 200
        use-dns: false
      dhcp6: false"

# 2 NICs, ens0 + ens0s1 ---------------------------------------------
# Regression: primary must be chosen by PCI device-path order, not
# by MAC. ens0 has the higher MAC but the lower PCI device number,
# so it must come first; ens0s1 must come second.
setup_2nic_ens_pci() {
    make_nic "$1" ens0   00:0d:3a:00:00:99 mana
    make_nic "$1" ens0s1 00:0d:3a:00:00:01 mana
}
expected_2nic_ens_pci="${HEADER}
    enx000d3a000099:
      match:
        macaddress: 00:0d:3a:00:00:99
        driver: mana
      dhcp4: true
      dhcp4-overrides:
        route-metric: 100
      dhcp6: false
    enx000d3a000001:
      match:
        macaddress: 00:0d:3a:00:00:01
        driver: mana
      dhcp4: true
      dhcp4-overrides:
        route-metric: 200
        use-dns: false
      dhcp6: false"

# 2 NICs, ens1 (dev_port 0) + ens1d1 (dev_port 1) -------------------
# Regression: a multi-port NIC where both interfaces share the same
# parent PCI device. The kernel disambiguates them only via
# dev_port; ens1 (dev_port 0, higher MAC) must be primary, ens1d1
# (dev_port 1) must be secondary. Mirrors a real Azure observation:
#   $ cat ens1/dev_port    -> 0
#   $ cat ens1d1/dev_port  -> 1
setup_2nic_ens_devport() {
    make_nic "$1" ens1   00:0d:3a:00:00:99 mana "" 0 mana_pf0
    make_nic "$1" ens1d1 00:0d:3a:00:00:01 mana "" 1 mana_pf0
}
expected_2nic_ens_devport="${HEADER}
    enx000d3a000099:
      match:
        macaddress: 00:0d:3a:00:00:99
        driver: mana
      dhcp4: true
      dhcp4-overrides:
        route-metric: 100
      dhcp6: false
    enx000d3a000001:
      match:
        macaddress: 00:0d:3a:00:00:01
        driver: mana
      dhcp4: true
      dhcp4-overrides:
        route-metric: 200
        use-dns: false
      dhcp6: false"

# ---- Run -----------------------------------------------------------

run_test "1 NIC, no AN"                   setup_1nic_no_an       "${expected_1nic_no_an}"
run_test "2 NICs, no AN"                  setup_2nic_no_an       "${expected_2nic_no_an}"
run_test "4 NICs, no AN"                  setup_4nic_no_an       "${expected_4nic_no_an}"
run_test "2 NICs, mlx5 AN (VFs filtered)" setup_2nic_mlx_an      "${expected_2nic_mlx_an}"
run_test "2 NICs, mana AN (VFs filtered)" setup_2nic_mana_an     "${expected_2nic_mana_an}"
run_test "2 NICs, mana-only"              setup_2nic_mana_only   "${expected_2nic_mana_only}"
run_test "2 NICs, ens0+ens0s1 PCI order"  setup_2nic_ens_pci     "${expected_2nic_ens_pci}"
run_test "2 NICs, ens1+ens1d1 dev_port"   setup_2nic_ens_devport "${expected_2nic_ens_devport}"

echo
echo "Passed: ${PASS}  Failed: ${FAIL}"
[ "${FAIL}" -eq 0 ]
