#!/bin/bash
# generate-stable-netplan.sh
#
# Disable cloud-init networking and write /etc/netplan/10-stable.yaml
# matching cloud-init's
# generate_network_config_from_instance_network_metadata() with
# apply_network_config_set_name=false (PR canonical/cloud-init#6807):
# stanzas keyed by enx<MAC>, matched by MAC, no set-name; primary
# (current eth0, typically hv_netvsc) gets route-metric 100;
# secondaries get (idx+1)*100 + use-dns:false.
#
# Structured as functions so it can be unit-tested with synthetic
# /sys/class/net trees: see tests/test-generate-stable-netplan.sh.
# All sysfs reads honor $SYSFS_NET (default /sys/class/net).

set -eu

SYSFS_NET=${SYSFS_NET:-/sys/class/net}
NETPLAN_DIR=${NETPLAN_DIR:-/etc/netplan}
CLOUD_CFG_DIR=${CLOUD_CFG_DIR:-/etc/cloud/cloud.cfg.d}
STABLE_FILE=${STABLE_FILE:-${NETPLAN_DIR}/10-stable.yaml}

# enumerate_nics
#   Print one line per real ethernet NIC found under $SYSFS_NET:
#       <mac> <ifname> <driver>
#   Output is sorted by (realpath of the NIC's `device` symlink,
#   `dev_port`). On Azure that corresponds to PCI slot / VMBus offer
#   order, then port number within a multi-port device. That is the
#   order the kernel itself uses to assign eth0, eth1, … (and
#   matches the udev `ID_NET_NAME_PATH` derivation that gives e.g.
#   `ens1` dev_port 0 vs `ens1d1` dev_port 1), so the first row is
#   always the hardware-primary NIC.
#   Skips: lo, virtual devices, all-zero MACs, and Azure VFs
#   transparently enslaved to a synthetic NIC (the VF has a `master`
#   symlink in sysfs).
enumerate_nics() {
    local d ifname mac driver devpath devport
    for d in "${SYSFS_NET}"/*; do
        [ -e "${d}/device" ] || continue
        [ "$(cat "${d}/type" 2>/dev/null || echo)" = 1 ] || continue
        # Skip transparent VFs (enslaved to a synthetic NIC).
        [ -e "${d}/master" ] && continue
        ifname=$(basename "${d}")
        mac=$(tr 'A-Z' 'a-z' < "${d}/address" 2>/dev/null || echo)
        [ -n "${mac}" ] && [ "${mac}" != 00:00:00:00:00:00 ] || continue
        driver=$(basename "$(readlink -f "${d}/device/driver" 2>/dev/null)" \
                 2>/dev/null || echo unknown)
        devpath=$(readlink -f "${d}/device" 2>/dev/null || echo "${d}")
        # dev_port disambiguates multiple ports on the same PCI
        # device (e.g. ens1 dev_port=0 vs ens1d1 dev_port=1). Pad
        # so lexical sort matches numeric sort up to 4 digits.
        devport=$(printf '%04d' "$(cat "${d}/dev_port" 2>/dev/null || echo 0)")
        # Prepend (devpath, devport) as the sort key; strip after
        # sorting so the final output is `<mac> <ifname> <driver>`.
        printf '%s\t%s\t%s %s %s\n' \
            "${devpath}" "${devport}" "${mac}" "${ifname}" "${driver}"
    done | sort | cut -f3-
}

# pick_primary_mac <enumerate_nics output>
#   Print the MAC of the primary NIC. The input is already in
#   hardware order (see enumerate_nics), so "first matching row" is
#   the lowest-numbered PCI slot / earliest VMBus offer that meets
#   the criterion. Preference order:
#     1. NIC currently named eth0 (Azure pins hv_netvsc to eth0).
#     2. First hv_netvsc NIC in hardware order.
#     3. First mana NIC in hardware order (mana-only future SKUs).
#     4. First NIC overall in hardware order.
#   Hardware order matters: e.g. on a VM with `ens0` and `ens0s1`,
#   `ens0` (lower PCI device number) is the primary, not `ens0s1`,
#   regardless of which one happens to have the lower MAC.
pick_primary_mac() {
    awk '
        $2=="eth0" {print $1; exit}
        $3=="hv_netvsc" && !hv {hv=$1}
        $3=="mana"     && !mn {mn=$1}
        !any {any=$1}
        END {
            if (hv)  print hv
            else if (mn) print mn
            else if (any) print any
        }
    '
}

# render_netplan <primary_mac> <enumerate_nics output>
#   Write the stable netplan YAML to stdout. Each stanza matches by
#   both macaddress and driver: on Azure the synthetic NIC
#   (hv_netvsc) and its accelerated-networking VF (mlx5_core, mana)
#   share a MAC, so a MAC-only match would non-deterministically
#   bind to the VF.
render_netplan() {
    local primary=$1 nics=$2 idx=0 mac driver
    cat <<EOF
# Generated by generate-stable-netplan.sh on $(date -u +%FT%TZ).
# Mirrors cloud-init PR #6807 (apply_network_config_set_name=false):
# enx<MAC> stanzas, MAC + driver match, no set-name (kernel keeps
# eth0/etc). Driver match is required to avoid binding to the AN VF.
network:
  version: 2
  renderer: networkd
  ethernets:
EOF
    # Primary first, then the rest in hardware (sysfs device-path) order.
    for mac in "${primary}" $(echo "${nics}" | awk -v p="${primary}" '$1!=p{print $1}'); do
        driver=$(echo "${nics}" | awk -v m="${mac}" '$1==m{print $3; exit}')
        printf '    enx%s:\n' "$(echo "${mac}" | tr -d :)"
        printf '      match:\n'
        printf '        macaddress: %s\n' "${mac}"
        printf '        driver: %s\n' "${driver}"
        printf '      dhcp4: true\n'
        printf '      dhcp4-overrides:\n'
        printf '        route-metric: %d\n' "$(( (idx + 1) * 100 ))"
        [ "${idx}" -gt 0 ] && printf '        use-dns: false\n'
        printf '      dhcp6: false\n'
        idx=$((idx + 1))
    done
}

# disable_cloud_init_networking
#   Drop the cloud.cfg.d snippet and remove cloud-init netplan files.
disable_cloud_init_networking() {
    mkdir -p "${NETPLAN_DIR}" "${CLOUD_CFG_DIR}"
    echo 'network: {config: disabled}' \
        > "${CLOUD_CFG_DIR}/99-disable-network-config.cfg"
    rm -f "${NETPLAN_DIR}"/50-cloud-init.yaml \
          "${NETPLAN_DIR}"/90-cloud-init-*.yaml
}

# main
main() {
    [ "$(id -u)" -eq 0 ] || { echo "run as root" >&2; exit 1; }

    local nics primary
    nics=$(enumerate_nics)
    [ -n "${nics}" ] || { echo "no ethernet NICs found" >&2; exit 1; }
    primary=$(printf '%s\n' "${nics}" | pick_primary_mac)
    [ -n "${primary}" ] || { echo "could not determine primary NIC" >&2; exit 1; }

    disable_cloud_init_networking
    render_netplan "${primary}" "${nics}" > "${STABLE_FILE}"
    chmod 0600 "${STABLE_FILE}"
    echo "Wrote ${STABLE_FILE}"
    echo "Review then: netplan generate && netplan apply"
}

# Allow sourcing for tests without running main.
if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    main "$@"
fi
